### PR TITLE
Ignore error when new column is added to DB schema (allow backward-compatible migrations)

### LINKED ISSUE #13: Pgkit is not backward-compatible when a new column is added to a DB table schema
When I add a new column to the DB schema (e.g. v2 of my application)
```diff
+ new_field BOOLEAN NOT NULL DEFAULT TRUE
```
and apply the migration, the old v1 application will start failing on all `SELECT * FROM` pgkit queries with the following error:
```
get collection by contract address:
  get one:
    pgkit: scanning: doing scan: scanFn:
      scany: column: 'new_field': no corresponding field found, or it's unexported in data.Collection
```

This effectively prevent us from writing backward-compatible schema upgrades, since we can't add new columns without breaking the already running applications with slightly older Go data models.

Expected behavior: The old v1 application should ignore any new columns, which don't have corresponding fields found in the struct.

### PR DESCRIPTION
**Pull request by VojtechVitek**
Fixes #13 -- Pgkit is not backward-compatible when a new column is added to a DB table schema

### CODE REVIEW

File: tests/testdata/pgkit_test_db.sql [hunk 1]
```diff
@@ -2,6 +2,7 @@ CREATE TABLE accounts (
   id SERIAL PRIMARY KEY,
   name VARCHAR(255),
   disabled BOOLEAN,
+  new_column_not_in_code BOOLEAN, -- test for backward-compatible migrations, see https://github.com/goware/pgkit/issues/13
```
Comment (VojtechVitek) [inline tests/testdata/pgkit_test_db.sql:5]: This used to fail with
```
=== RUN   TestSugarInsertAndSelectRows
    pgkit_test.go:67: 
        	Error Trace:	/home/runner/work/pgkit/pgkit/tests/pgkit_test.go:67
        	Error:      	Received unexpected error:
        	            	pgkit: scanning: scanning: doing scan: scanFn: scany: column: 'new_column_not_in_code': no corresponding field found, or it's unexported in pgkit_test.Account
        	Test:       	TestSugarInsertAndSelectRows
    pgkit_test.go:68: 
        	Error Trace:	/home/runner/work/pgkit/pgkit/tests/pgkit_test.go:68
        	Error:      	"[]" should have 1 item(s), but has 0
        	Test:       	TestSugarInsertAndSelectRows
```
